name: MongoDB Database Cleanup

on:
  schedule:
    - cron: '0 0 1 * *'  # On the 1st of every month at 00:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup:
    name: Clean MongoDB Databases
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run cleanup script
        run: npm start
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DATABASES_TO_CLEAN: ${{ secrets.DATABASES_TO_CLEAN }}
